Repository MODFLOW-ORG/modflow6, pull requests merged in 2023-12, with the labels that each got.

#1489 refactor(logging): consolidate logging routines in Message.f90
  autotest/TestMessage.f90
  autotest/meson.build
  autotest/tester.f90
  make/makefile
  src/Model/GroundWaterFlow/gwf3csub8.f90
  src/Model/GroundWaterFlow/gwf3lak8.f90
  src/Model/GroundWaterFlow/gwf3uzf8.f90
  src/Model/ModelUtilities/Connections.f90
  src/SimulationCreate.f90
  src/Solution/LinearMethods/ims8base.f90
  src/Solution/LinearMethods/ims8linear.f90
  src/Solution/NumericalSolution.f90
  src/Timing/tdis.f90
  src/Utilities/Idm/SourceLoad.F90
  src/Utilities/InputOutput.f90
  src/Utilities/Message.f90
  src/Utilities/Sim.f90
  src/Utilities/Timer.f90
  src/Utilities/comarg.f90
  src/Utilities/genericutils.f90
  src/Utilities/version.f90
  src/mf6core.f90
  srcbmi/mf6bmiUtil.f90
  utils/mf5to6/make/makefile
  utils/mf5to6/msvs/mf5to6.vfproj
  utils/mf5to6/pymake/extrafiles.txt
  utils/mf5to6/src/MF2005/GwfBasSubs.f
  utils/mf5to6/src/ModelConverter.f90
  utils/mf5to6/src/Preproc/Preproc.f90
  utils/zonebudget/make/makefile
  utils/zonebudget/src/zbud6.f90
Labels: code refactor, maintenance

#1446 refactor: introduce MathUtilModule, move is_same, add tests
  autotest/TestMathUtil.f90
  make/makefile
  msvs/mf6core.vfproj
  msvs/mf6lib.vfproj
  pymake/makefile
  src/Model/Connection/GridSorting.f90
  src/Model/GroundWaterFlow/gwf3csub8.f90
  src/Model/GroundWaterFlow/gwf3lak8.f90
  src/Solution/LinearMethods/ims8base.f90
  src/Solution/NumericalSolution.f90
  src/Utilities/InputOutput.f90
  src/Utilities/MathUtil.f90
  src/Utilities/TimeSeries/TimeArraySeries.f90
  src/Utilities/TimeSeries/TimeSeries.f90
  src/Utilities/genericutils.f90
  src/meson.build
  utils/mf5to6/make/makefile
  utils/mf5to6/msvs/mf5to6.vfproj
  utils/mf5to6/pymake/extrafiles.txt
  utils/mf5to6/src/MultiLayerObsModule.f90
  utils/mf5to6/src/Preproc/ObsBlock.f90
  utils/mf5to6/src/Preproc/ObservePHMF.f90
  utils/zonebudget/make/makefile
  utils/zonebudget/msvs/zonebudget.vfproj
  utils/zonebudget/pymake/extrafiles.txt
Labels: code refactor, maintenance

#1504 fix(gwt-mwt.dfn): typo
  doc/mf6io/mf6ivar/dfn/gwt-mwt.dfn
Labels: documentation

#1503 fix(gwt-lkt.dfn): typo
  doc/mf6io/mf6ivar/dfn/gwt-lkt.dfn
Labels: documentation

#1492 chore(tdis.f90): cleanup docstrings in tdis class
  src/Timing/tdis.f90
  src/Utilities/Constants.f90
Labels: maintenance
