Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-07, with the labels that each got.

#1919 docs(prt-oc): add subsection describing tracking events
  doc/mf6io/prt/oc.tex
Labels: documentation

#1921 fix(prp): fix incorrectly raised error introduced in 12dea73
  .github/workflows/ci.yml
  autotest/pytest.ini
  autotest/test_prt_notebooks.py
  environment.yml
  pixi.lock
  pixi.toml
  src/Model/ParticleTracking/prt-prp.f90
Labels: bug, dependencies, ci

#1924 doc(mf6io): fix several issues in IO guide
  doc/mf6io/gwe/gwe.tex
  doc/mf6io/gwf/ic.tex
  doc/mf6io/gwf/info_existing_users.tex
Labels: bug, documentation

#1923 refactor(oc): introduce module/type for time step selection
  autotest/TestTimeStepSelect.f90
  autotest/meson.build
  autotest/tester.f90
  make/makedefaults
  make/makefile
  msvs/mf6core.vfproj
  src/Model/GroundWaterFlow/gwf-oc.f90
  src/Model/GroundWaterTransport/gwt-ist.f90
  src/Model/ModelUtilities/TimeStepSelect.f90
  src/Model/ParticleTracking/prt-oc.f90
  src/Model/SurfaceWaterFlow/swf-oc.f90
  src/Model/TransportModel/tsp-oc.f90
  src/Utilities/OutputControl/OutputControl.f90
  src/Utilities/OutputControl/OutputControlData.f90
  src/Utilities/OutputControl/PrintSaveManager.f90
  src/meson.build
  utils/mf5to6/make/makedefaults
  utils/mf5to6/make/makefile
  utils/zonebudget/make/makedefaults
  utils/zonebudget/make/makefile
Labels: code refactor

#1926 fix(meson.build): separate parallel/extended dependencies
  .github/actions/test-extended/action.yml
  meson.build
Labels: parallel, dependencies, ci

#1931 doc(mf6io): fix PRT MIP section in IO guide
  doc/mf6io/prt/mip.tex
Labels: bug, documentation

#1930 fix(gwf-uzf.f90): auxmultname option not working as expected
  autotest/test_gwf_uzf_auxmult.py
  doc/ReleaseNotes/develop.tex
  src/Model/GroundWaterFlow/gwf-uzf.f90
Labels: bug

#1950 fix(tsp-obs): the OBS utility in GWE not supporting TEMPERATURE keyword
  autotest/test_gwe_obs.py
  doc/ReleaseNotes/develop.tex
  src/Model/Connection/GweInterfaceModel.f90
  src/Model/Connection/GwtInterfaceModel.f90
  src/Model/ModelUtilities/BoundaryPackage.f90
  src/Model/TransportModel/tsp-obs.f90
  src/Model/TransportModel/tsp.f90
Labels: bug

#1963 ci(parallel): run parallel build against serial tests
  .github/actions/test-par-win/action.yml
  .github/actions/test-par/action.yml
  .github/common/test_modflow6_parallel.bat
  .github/common/test_modflow6_serial.bat
  .github/workflows/ci.yml
Labels: parallel, ci

#1966 ci: add jobs to build/test with gfortran in debug mode
  .github/workflows/ci.yml
  autotest/test_prt_disv1.py
Labels: ci
