Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-02, with the labels that each got.

#1583 chore(BudgetObject.f90): cleanup docstrings in BudgetObject utility
  src/Utilities/BudgetObject.f90
  src/Utilities/BudgetTerm.f90
Labels: maintenance

#1582 fix(par): first version of message cache for MPI traffic
  make/makefile
  msvs/mf6core.vfproj
  pymake/excludefiles.txt
  src/Distributed/MpiMessageBuilder.f90
  src/Distributed/MpiMessageCache.f90
  src/Distributed/MpiRouter.f90
  src/Distributed/MpiRunControl.F90
  src/Distributed/MpiUnitCache.f90
  src/Distributed/MpiWorld.f90
  src/Distributed/VirtualDataContainer.f90
  src/Model/Connection/GwfGwfConnection.f90
  src/Solution/PETSc/PetscConvergence.F90
  src/Solution/ParallelSolution.f90
  src/Utilities/STLVecInt.f90
  src/Utilities/SimStages.f90
  src/meson.build
  utils/mf5to6/make/makefile
Labels: enhancement, parallel

#1600 chore(timer.f90): cleanup docstrings in Timer utility
  src/Utilities/Timer.f90
Labels: maintenance

#1625 ci(release): add distribution for apple silicon
  .github/workflows/release.yml
  .github/workflows/release_dispatch.yml
Labels: ci

#1603 refactor(dfn2f90): use dfns.txt input file, add options
  make/makefile
  msvs/mf6core.vfproj
  src/Idm/exg-gwegweidm.f90
  src/Idm/exg-gwfgweidm.f90
  src/Idm/exg-gwfgwfidm.f90
  src/Idm/exg-gwfgwtidm.f90
  src/Idm/exg-gwtgwtidm.f90
  src/Idm/exg-swfgwfidm.f90
  src/Idm/gwe-cndidm.f90
  src/Idm/gwe-ctpidm.f90
  src/Idm/gwe-disidm.f90
  src/Idm/gwe-disuidm.f90
  src/Idm/gwe-disvidm.f90
  src/Idm/gwe-icidm.f90
  src/Idm/gwe-namidm.f90
  src/Idm/gwf-chdidm.f90
  src/Idm/gwf-disidm.f90
  src/Idm/gwf-disuidm.f90
  src/Idm/gwf-disvidm.f90
  src/Idm/gwf-drnidm.f90
  src/Idm/gwf-evtaidm.f90
  src/Idm/gwf-evtidm.f90
  src/Idm/gwf-ghbidm.f90
  src/Idm/gwf-icidm.f90
  src/Idm/gwf-namidm.f90
  src/Idm/gwf-npfidm.f90
  src/Idm/gwf-rchaidm.f90
  src/Idm/gwf-rchidm.f90
  src/Idm/gwf-rividm.f90
  src/Idm/gwf-welidm.f90
  src/Idm/gwt-cncidm.f90
  src/Idm/gwt-disidm.f90
  src/Idm/gwt-disuidm.f90
  src/Idm/gwt-disvidm.f90
  src/Idm/gwt-dspidm.f90
  src/Idm/gwt-icidm.f90
  src/Idm/gwt-namidm.f90
  src/Idm/selector/IdmDfnSelector.f90
  src/Idm/selector/IdmExgDfnSelector.f90
  src/Idm/selector/IdmGweDfnSelector.f90
  src/Idm/selector/IdmGwfDfnSelector.f90
  src/Idm/selector/IdmGwtDfnSelector.f90
  src/Idm/selector/IdmSimDfnSelector.f90
  src/Idm/selector/IdmSwfDfnSelector.f90
  src/Idm/sim-namidm.f90
  src/Idm/sim-tdisidm.f90
  src/Idm/swf-chdidm.f90
  src/Idm/swf-cxsidm.f90
  src/Idm/swf-dfwidm.f90
  src/Idm/swf-dislidm.f90
  src/Idm/swf-flwidm.f90
  src/Idm/swf-icidm.f90
  src/Idm/swf-namidm.f90
  src/Idm/swf-zdgidm.f90
  src/meson.build
  utils/idmloader/IDM.md
  utils/idmloader/dfns.txt
  utils/idmloader/scripts/dfn2f90.py
Labels: code refactor
