Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-06, with the labels that each got.

#1853 fix: build windows parallel with ifort 2021.12
  .github/actions/setup-par-oneapi/action.yml
Labels: bug, parallel, ci

#1859 ci(macos-14): use gcc12 on macos-14, workaround is_recursive symbol missing
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: nightly build, ci

#1869 feat(par): add model columns to convergence csv for completeness in parallel case
  src/Solution/NumericalSolution.f90
Labels: enhancement, parallel

#1874 fix(prt): multiple fixes
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[1-0-prtqref01].npy
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[2-0-prtqref01].npy
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[pollock-1-0-prtqref01].npy
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[pollock-2-0-prtqref01].npy
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[ternary-1-0-prtqref01].npy
  autotest/__snapshots__/test_prt_quad_refinement/test_mf6model[ternary-2-0-prtqref01].npy
  autotest/test_prt_quad_refinement.py
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
  src/Utilities/GeomUtil.f90
Labels: bug

#1871 docs(release): mention #1865 in release notes
  doc/ReleaseNotes/develop.tex
Labels: documentation

#1870 docs: add style guide, tidy dev/contrib docs, update docs sites
  .build_rtd_docs/Doxyfile
  .build_rtd_docs/MAINPAGE.md
  .build_rtd_docs/conf.py
  .build_rtd_docs/index.rst
  .build_rtd_docs/mf6io.rst
  .build_rtd_docs/styleguide.md
  .doc/conf.py
  .github/common/update_fortran_style.py
  CONTRIBUTING.md
  DEVELOPER.md
  distribution/README.md
  distribution/benchmark.py
Labels: help wanted, documentation, maintenance

#1888 fix(prt): make extended tracking opt-in
  autotest/test_prt_budget.py
  autotest/test_prt_disv1.py
  autotest/test_prt_drape.py
  autotest/test_prt_exg.py
  autotest/test_prt_fmi.py
  autotest/test_prt_quad_refinement.py
  autotest/test_prt_release_timing.py
  autotest/test_prt_stop_zones.py
  autotest/test_prt_ternary_methods.py
  autotest/test_prt_track_events.py
  autotest/test_prt_triangle.py
  autotest/test_prt_voronoi1.py
  autotest/test_prt_voronoi2.py
  autotest/test_prt_weak_sinks.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  doc/mf6io/mf6ivar/md/mf6ivar.md
  doc/mf6io/mf6ivar/tex/prt-prp-desc.tex
  doc/mf6io/mf6ivar/tex/prt-prp-options.dat
  doc/mf6io/prt/prt.tex
  src/Model/ParticleTracking/prt-prp.f90
  src/Model/ParticleTracking/prt.f90
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
  src/Solution/ParticleTracker/Particle.f90
Labels: bug, documentation, option

#1882 refactor(gwe-est): remove packagedata block and put values in options block
  autotest/test_gwe_cnd.py
  autotest/test_gwe_drycell_cnd0.py
  autotest/test_gwe_drycell_cnd1.py
  autotest/test_gwe_drycell_cnd2.py
  autotest/test_gwe_drycell_cnd4.py
  autotest/test_gwe_esl01.py
  autotest/test_gwe_esl02.py
  autotest/test_gwe_esl_analyt_sln.py
  autotest/test_gwe_lke_conduction.py
  autotest/test_gwe_mve.py
  autotest/test_gwe_mwe_conduction.py
  autotest/test_gwe_sfe_strmbedcond.py
  autotest/test_gwe_split_analyt.py
  autotest/test_gwe_stallman.py
  autotest/test_gwe_uze00.py
  autotest/test_gwe_vs_gwt.py
  autotest/test_gwegwe_exchng_with_comp2gwt.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/gwe/est.tex
  doc/mf6io/mf6ivar/dfn/gwe-est.dfn
  doc/mf6io/mf6ivar/examples/gwe-est-example.dat
  doc/mf6io/mf6ivar/md/mf6ivar.md
  doc/mf6io/mf6ivar/tex/appendixA.tex
  doc/mf6io/mf6ivar/tex/gwe-est-desc.tex
  doc/mf6io/mf6ivar/tex/gwe-est-options.dat
  doc/mf6io/mf6ivar/tex/gwe-est-packagedata.dat
  src/Model/GroundWaterEnergy/gwe-est.f90
  src/Model/ModelUtilities/GweInputData.f90
Labels: documentation, code refactor

#1900 fix(prt): sum boundary and face flows when loading cell
  doc/ReleaseNotes/develop.tex
  src/Solution/ParticleTracker/MethodDis.f90
  src/Solution/ParticleTracker/MethodDisv.f90
Labels: bug

#1902 docs(prt): fix typos in mf6io document
  doc/mf6io/prt/fmi.tex
Labels: documentation

#1903 ci(release): omit backwards particle tracking examples
  distribution/build_dist.py
Labels: examples, ci

#1907 refactor(prp): factor out routine for particle release
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  src/Model/ParticleTracking/prt-prp.f90
  src/Model/ParticleTracking/prt.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
  src/Solution/ParticleTracker/Particle.f90
Labels: code refactor

#1918 fix(prt): fix pass-to-bottom tracking method
  doc/ReleaseNotes/develop.tex
  src/Solution/ParticleTracker/MethodCellPassToBot.f90
Labels: bug
