Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-08, with the labels that each got.

#1990 docs(prt): indicate that multiple PRPs are allowed
  doc/mf6io/prt/namefile.tex
Labels: bug, documentation

#1980 ci: reclaim disk space on ubuntu for intel test job
  .github/workflows/ci.yml
Labels: bug, ci

#1989 fix(prt): fix track- and release-time file reading, update docs
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-2-prtreltopen].npy
  autotest/test_prt_disv1.py
  autotest/test_prt_release_timing.py
  autotest/test_prt_track_events.py
  autotest/test_prt_voronoi1.py
  doc/mf6io/mf6ivar/dfn/prt-oc.dfn
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  src/Model/ParticleTracking/prt-oc.f90
  src/Model/ParticleTracking/prt-prp.f90
Labels: bug, documentation

#1928 fix(prt): fix duplicate particles, tidier release mechanism
  autotest/TestMathUtil.f90
  autotest/TestTimeSelect.f90
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-0-prtreltsgl].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-1-prtreltdbl].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-2-prtreltopen].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-3-prtreltall].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-4-prtreltfrst].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-5-prtreltstps].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[0.5-6-prtreltfreq].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltall].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltboth].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltdbl].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltdupe].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltfreq].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltfrst].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltopen].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltsgl].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtreltstps].npy
  autotest/__snapshots__/test_prt_release_timing/test_mf6model[prtrelttol].npy
  autotest/test_prt_disv1.py
  autotest/test_prt_release_timing.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  make/makefile
  msvs/mf6core.vfproj
  src/Model/ModelUtilities/ReleaseSchedule.f90
  src/Model/ModelUtilities/TimeSelect.f90
  src/Model/ModelUtilities/TimeStepSelect.f90
  src/Model/ParticleTracking/prt-prp.f90
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
  src/Solution/ParticleTracker/Particle.f90
  src/Utilities/MathUtil.f90
  src/Utilities/OutputControl/OutputControlData.f90
  src/meson.build
  utils/mf5to6/make/makefile
  utils/zonebudget/make/makefile
Labels: bug, code refactor, option

#2001 refactor(gwe-est): rename variables rhos and cps to density_solid and heat_capacity_solid
  autotest/test_gwe_cnd.py
  autotest/test_gwe_drycell_cnd0.py
  autotest/test_gwe_drycell_cnd1.py
  autotest/test_gwe_drycell_cnd2.py
  autotest/test_gwe_drycell_cnd4.py
  autotest/test_gwe_esl01.py
  autotest/test_gwe_esl02.py
  autotest/test_gwe_esl_analyt_sln.py
  autotest/test_gwe_lke_conduction.py
  autotest/test_gwe_mve.py
  autotest/test_gwe_mwe_conduction.py
  autotest/test_gwe_obs.py
  autotest/test_gwe_sfe_strmbedcond.py
  autotest/test_gwe_split_analyt.py
  autotest/test_gwe_stallman.py
  autotest/test_gwe_uze00.py
  autotest/test_gwe_vs_gwt.py
  autotest/test_gwegwe_exchng_with_comp2gwt.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/mf6ivar/dfn/gwe-est.dfn
  doc/mf6io/mf6ivar/examples/gwe-est-example.dat
  src/Model/GroundWaterEnergy/gwe-est.f90
Labels: maintenance

#2005 docs(prt): update structure of blocks section for prp/oc
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  doc/mf6io/prt/oc.tex
  doc/mf6io/prt/prp.tex
Labels: bug, documentation
