Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-11, with the labels that each got.

#2043 fix(PrtFmiType): accommodate 0s in nodelist
  doc/ReleaseNotes/develop.tex
  src/Model/ParticleTracking/prt-fmi.f90
Labels: bug

#2055 refactor(prt): split TrackData into separate file and control modules
  make/makefile
  msvs/mf6core.vfproj
  src/Model/ModelUtilities/TrackControl.f90
  src/Model/ModelUtilities/TrackData.f90
  src/Model/ModelUtilities/TrackFile.f90
  src/Model/ParticleTracking/prt-oc.f90
  src/Model/ParticleTracking/prt-prp.f90
  src/Model/ParticleTracking/prt.f90
  src/Solution/ParticleTracker/Method.f90
  src/Solution/ParticleTracker/MethodCellPassToBot.f90
  src/Solution/ParticleTracker/MethodCellPollock.f90
  src/Solution/ParticleTracker/MethodCellPollockQuad.f90
  src/Solution/ParticleTracker/MethodCellTernary.f90
  src/Solution/ParticleTracker/MethodDis.f90
  src/Solution/ParticleTracker/MethodDisv.f90
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
  src/meson.build
Labels: code refactor

#2063 chore(scripts): remove check_spelling.py
  .codespellrc
  .github/common/check_spelling.py
  .vscode/tasks.json
  DEVELOPER.md
  pixi.toml
Labels: code refactor, ci

#2064 ci(macos): switch macos-12 -> 13, trim compiler compat test matrix
  .github/workflows/ci.yml
  .github/workflows/compilers.yml
Labels: ci

#1951 fix(UzfCellGroup): SQUARE_GWET option records ET as inflow instead of outflow
  autotest/TestUzfEtUtil.f90
  autotest/test_gwf_uzf_gwet_opt.py
  doc/ReleaseNotes/develop.tex
  src/Model/ModelUtilities/UzfCellGroup.f90
  src/Model/ModelUtilities/UzfEtUtil.f90
Labels: bug
