Repository MODFLOW-ORG/modflow6, pull requests merged in 2024-04, with the labels that each got.

#1709 fix(prt): set tmax properly before particle solve
  autotest/test_prt_disv1.py
  src/Model/ModelUtilities/TrackData.f90
  src/Model/ParticleTracking/prt.f90
  src/Solution/ParticleTracker/Method.f90
  src/Solution/ParticleTracker/MethodCellPassToBot.f90
  src/Solution/ParticleTracker/MethodCellPollock.f90
  src/Solution/ParticleTracker/MethodCellPollockQuad.f90
  src/Solution/ParticleTracker/MethodCellTernary.f90
  src/Solution/ParticleTracker/MethodDis.f90
  src/Solution/ParticleTracker/MethodDisv.f90
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
Labels: bug

#1738 fix(par): GNC is not supported in parallel
  src/Distributed/MpiRunControl.F90
  src/Distributed/MpiWorld.f90
  src/Exchange/exg-gwfgwf.f90
  src/Model/Connection/GwfGwfConnection.f90
  src/Utilities/ErrorUtil.f90
Labels: bug

#1750 fix(par): XT3D on exchange no longer hangs simulation
  autotest/test_par_gwf04.py
  src/Distributed/InterfaceMap.f90
  src/Distributed/MpiRouter.f90
  src/Distributed/MpiRunControl.F90
  src/Distributed/RouterBase.f90
  src/Distributed/VirtualDataContainer.f90
  src/Distributed/VirtualDataManager.f90
  src/Model/Connection/SpatialModelConnection.f90
  src/RunControl.f90
  src/Utilities/ArrayHandlers.f90
Labels: bug, parallel

#1752 ci(release): fix model selection options for dist scripts
  .github/workflows/release.yml
  autotest/get_exes.py
  distribution/build_dist.py
Labels: bug, ci
