Repository MODFLOW-ORG/modflow6, pull requests merged in 2025-01, with the labels that each got.

#2126 docs(prp): fix removal version of fraction option
  .codespellrc
  .github/workflows/ci.yml
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  doc/mf6io/mf6ivar/mf6ivar.py
  environment.yml
  pixi.lock
  pixi.toml
Labels: documentation, dependencies

#2127 fix(prt): skip release times falling outside tdis
  doc/ReleaseNotes/develop.tex
  doc/mf6io/mf6ivar/dfn/prt-prp.dfn
  src/Model/ModelUtilities/ReleaseSchedule.f90
  src/Model/ParticleTracking/prt-prp.f90
Labels: bug

#2129 fix(prp): fix error msg format, improve msg
  src/Model/ParticleTracking/prt-prp.f90
Labels: documentation

#2131 fix(prt): don't reset transform in subcell rect method
  src/Solution/ParticleTracker/CellDefn.f90
  src/Solution/ParticleTracker/Method.f90
  src/Solution/ParticleTracker/MethodDisv.f90
  src/Solution/ParticleTracker/MethodSubcellPollock.f90
Labels: bug

#2150 docs(release): add release note for recent PRT fix
  doc/ReleaseNotes/develop.tex
Labels: documentation, release

#2149 fix(exg-gwf*): check for equal idomain
  autotest/test_prt_exg.py
  doc/ReleaseNotes/develop.tex
  src/Exchange/exg-gwfgwe.f90
  src/Exchange/exg-gwfgwt.f90
  src/Exchange/exg-gwfprt.f90
Labels: bug

#2151 docs(prt-fmi): clarify only required when post-processing
  autotest/test_prt_exg.py
  doc/mf6io/gwe/fmi.tex
  doc/mf6io/gwt/fmi.tex
  doc/mf6io/prt/fmi.tex
Labels: bug, documentation

#2153 feat(fmi): support binary grid file
  autotest/test_prt_fmi.py
  autotest/test_prt_voronoi2.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/gwe/fmi.tex
  doc/mf6io/gwt/fmi.tex
  doc/mf6io/mf6ivar/dfn/gwe-fmi.dfn
  doc/mf6io/mf6ivar/dfn/gwt-fmi.dfn
  doc/mf6io/mf6ivar/dfn/prt-fmi.dfn
  doc/mf6io/prt/fmi.tex
  make/makefile
  msvs/mf6core.vfproj
  src/Model/ModelUtilities/FlowModelInterface.f90
  src/Model/TransportModel/tsp-fmi.f90
  src/Utilities/GridFileReader.f90
  src/meson.build
  utils/mf5to6/make/makefile
  utils/zonebudget/make/makefile
  utils/zonebudget/meson.build
  utils/zonebudget/msvs/zonebudget.vfproj
  utils/zonebudget/pymake/extrafiles.txt
  utils/zonebudget/src/grb.f90
  utils/zonebudget/src/zbud6.f90
Labels: enhancement

#2155 fix(gwe-est): add support for energy decay in the solid phase
  autotest/test_gwe_decay01.py
  autotest/test_gwe_decay02.py
  doc/ReleaseNotes/develop.tex
  doc/mf6io/mf6ivar/dfn/gwe-est.dfn
  src/Model/GroundWaterEnergy/gwe-est.f90
  src/Model/GroundWaterTransport/gwt-mst.f90
Labels: bug
