Repository MODFLOW-ORG/modflow6, pull requests merged in 2025-04, with the labels that each got.

#2265 test: use devtools models api, misc cleanup
  .github/workflows/ci.yml
  .github/workflows/compilers.yml
  .github/workflows/large.yml
  .github/workflows/release.yml
  .gitignore
  autotest/compare.py
  autotest/framework.py
  autotest/test_largetestmodels.py
  autotest/test_testmodels_mf5to6.py
  autotest/test_testmodels_mf6.py
Labels: maintenance

#2270 docs(mf6io): modelname description incomplete in buy and vsc packages
  doc/mf6io/mf6ivar/dfn/gwf-buy.dfn
  doc/mf6io/mf6ivar/dfn/gwf-vsc.dfn
Labels: documentation

#2268 fix(gwe-sfe): add support for strmbd-cond observation type in sfe
  autotest/test_gwe_sfe_strmbedcond.py
  doc/ReleaseNotes/develop.toml
  src/Model/GroundWaterEnergy/gwe-sfe.f90
Labels: bug

#2281 fix(prt): fix vertical ternary method
  autotest/__snapshots__/test_prt_disv_vert/test_mf6model[0-prtdisvvert].npy
  autotest/prt_test_utils.py
  autotest/test_prt_disv_vert.py
  doc/ReleaseNotes/develop.toml
  src/Solution/ParticleTracker/MethodSubcellTernary.f90
Labels: bug

#2292 refactor(dfn2f90.py): accept 1+ dfn files or directories
  pixi.toml
  utils/idmloader/dfns.txt
  utils/idmloader/scripts/dfn2f90.py
Labels: maintenance
